// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVtTIBGTSM3z8CmL7gan_8qE2lt2Hv6F4',
    appId: '1:1080546603009:ios:74b2ee574e4e47bc6a9000',
    messagingSenderId: '1080546603009',
    projectId: 'women-safety-app-1e035',
    storageBucket: 'women-safety-app-1e035.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCioqox73fdxSqEqBXPNoH-1foAfDP-_24',
    appId: '1:1080546603009:web:378c56e383571d6b6a9000',
    messagingSenderId: '1080546603009',
    projectId: 'women-safety-app-1e035',
    authDomain: 'women-safety-app-1e035.firebaseapp.com',
    storageBucket: 'women-safety-app-1e035.firebasestorage.app',
    measurementId: 'G-VTZQM5LT02',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtTIBGTSM3z8CmL7gan_8qE2lt2Hv6F4',
    appId: '1:1080546603009:ios:74b2ee574e4e47bc6a9000',
    messagingSenderId: '1080546603009',
    projectId: 'women-safety-app-1e035',
    storageBucket: 'women-safety-app-1e035.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu3Q_0IiL4LHqlHetc-22jWlwOjhhRI4A',
    appId: '1:1080546603009:android:3f05226e9875a8836a9000',
    messagingSenderId: '1080546603009',
    projectId: 'women-safety-app-1e035',
    storageBucket: 'women-safety-app-1e035.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCioqox73fdxSqEqBXPNoH-1foAfDP-_24',
    appId: '1:1080546603009:web:e17b99e505fa549b6a9000',
    messagingSenderId: '1080546603009',
    projectId: 'women-safety-app-1e035',
    authDomain: 'women-safety-app-1e035.firebaseapp.com',
    storageBucket: 'women-safety-app-1e035.firebasestorage.app',
    measurementId: 'G-64F0W7V5RQ',
  );

}